name: Build Docker Image for Deployment

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_REGION: europe-west1
  GAR_REGISTRY_NAME: ${{ secrets.GAR_REGISTRY_NAME }}



jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GAR (Google Artifact Registry)
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GAR_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build Docker Image and Push to GAR
        run: |
          docker build -t ${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REGISTRY_NAME }}/analytics-endpoint:${{ github.sha }} .
          docker push ${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REGISTRY_NAME }}/analytics-endpoint:${{ github.sha }}
        